_format_version: "3.0"
_transform: true

services:
  - name: data-storage-service
    url: http://data-storage-service:8001
    plugins:
      - name: rate-limiting
        config:
          minute: 5000
          hour: 20000
      - name: cors
        config:
          origins: ["*"]
          methods: ["GET", "POST", "PUT", "DELETE"]
    routes:
      - name: data-storage-health
        paths: ["/health"]
        strip_path: false
      - name: data-storage-docs  
        paths: ["/docs"]
        strip_path: false
      - name: data-storage-info
        paths: ["/info"] 
        strip_path: false
      - name: data-storage-stats
        paths: ["/stats"]
        strip_path: false
      - name: data-storage-api
        paths: ["/api/v1/storage"]
        strip_path: true

  - name: fire-risk-service
    url: http://fire-risk-service:8000
    plugins:
      - name: rate-limiting
        config:
          minute: 1000
          hour: 5000
      - name: cors
        config:
          origins: ["*"]
          methods: ["GET", "POST", "PUT", "DELETE"]
    routes:
      - name: fire-risk-routes
        paths: ["/api/v1/fire-risk"]
        strip_path: true

  - name: data-ingestion-service
    url: http://data-ingestion-service:8000
    plugins:
      - name: rate-limiting
        config:
          minute: 2000
          hour: 10000
    routes:
      - name: data-ingestion-routes
        paths: ["/api/v1/ingestion"]
        strip_path: true

  - name: data-catalog-service
    url: http://data-catalog-service:8000
    plugins:
      - name: rate-limiting
        config:
          minute: 500
          hour: 2000
    routes:
      - name: data-catalog-routes
        paths: ["/api/v1/catalog"]
        strip_path: true

  - name: user-management-service
    url: http://user-management-service:8000
    plugins:
      - name: rate-limiting
        config:
          minute: 100
          hour: 500
    routes:
      - name: user-management-routes
        paths: ["/api/v1/auth", "/api/v1/users"]
        strip_path: true

  - name: visualization-service
    url: http://visualization-service:8000
    routes:
      - name: visualization-routes
        paths: ["/api/v1/viz"]
        strip_path: true

  - name: notification-service
    url: http://notification-service:8000
    routes:
      - name: notification-routes
        paths: ["/api/v1/notifications"]
        strip_path: true
