apiVersion: v2
name: wildfire-minio
description: MinIO on-premises object storage for CAL FIRE Wildfire Intelligence Platform (Hot Tier)
type: application
version: 1.0.0
appVersion: "RELEASE.2023-10-25"

keywords:
  - minio
  - storage
  - s3
  - object-storage
  - wildfire

home: https://min.io
sources:
  - https://github.com/minio/minio

maintainers:
  - name: CAL FIRE Architecture Team
    email: architecture@calfire.ca.gov

dependencies:
  - name: minio
    version: 5.0.14
    repository: https://charts.min.io/

annotations:
  challenge: "Challenge2-DataStorage"
  tier: "hot"
  compliance: "FISMA-Moderate,NIST-800-53,SOC2"
