global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files: []

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 15s

  - job_name: 'data-storage-service'
    static_configs:
      - targets: ['data-storage-service:8001']
    metrics_path: '/metrics'
    scrape_interval: 15s
    metric_relabel_configs:
      # Relabel metrics with exported_job to use that as the job label
      - source_labels: [exported_job]
        target_label: job
        action: replace

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
    scrape_interval: 30s

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 30s

  - job_name: 'minio'
    static_configs:
      - targets: ['minio:9000']
    scrape_interval: 30s

  - job_name: 'data-ingestion-service'
    static_configs:
      - targets: ['data-ingestion-service:8003']
    metrics_path: '/metrics'
    scrape_interval: 15s
