apiVersion: apps/v1
kind: Deployment
metadata:
  name: fire-risk-service
spec:
  template:
    spec:
      containers:
        - name: fire-risk
          resources:
            requests:
              memory: "2Gi"
              cpu: "1000m"
            limits:
              memory: "8Gi"
              cpu: "4000m"
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
spec:
  template:
    spec:
      containers:
        - name: postgres
          resources:
            requests:
              memory: "2Gi"
              cpu: "1000m"
            limits:
              memory: "8Gi"
              cpu: "4000m"
  volumeClaimTemplates:
    - metadata:
        name: postgres-storage
      spec:
        resources:
          requests:
            storage: 100Gi
