apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    user: admin
    database: wildfire
    basicAuth: false
    isDefault: false
    jsonData:
      version: Flux
      organization: wildfire
      defaultBucket: sensors
      tlsSkipVerify: true
    secureJsonData:
      token: wildfire-admin-token
