apiVersion: 1

datasources:
  - name: PostgreSQL-Wildfire
    type: postgres
    access: proxy
    url: wildfire-postgres:5432
    database: wildfire_db
    user: wildfire_user
    secureJsonData:
      password: wildfire_password
    jsonData:
      sslmode: disable
      maxOpenConns: 0
      maxIdleConns: 2
      connMaxLifetime: 14400
    isDefault: false
    editable: true